### ISSUE TITLE
结算页面不会正确跳转，原地卡死

### ISSUE THREAD

**Issue by littlegolden** [CHonesetDoPa/Mix-C#2]
触顶后画面原地不动

**Comment by Littlegolden** [comment]
不知是否跟这个位置有关系

![image](https://user-images.githubusercontent.com/35162802/106141578-46334880-61ab-11eb-8c7b-371c5d237990.png)

**Comment by CHonesetDoPa** [comment]
Emmmmm，这块大概是因为改掉了广告“ads.js”和右上角的浮窗导致的，我尽量改（www

**Comment by littlegolden** [comment]
实在不行就还原js吧，把首页的广告 id 清掉就差不多了。

**Comment by CHonesetDoPa** [comment]
www，会搞一个分支去修改的，大概也就这几天（逃

**Comment by littlegolden** [comment]
参照这里已修复 https://github.com/bullhe4d/bigwatermelon/compare/main...ZhentangHe:main#diff-3a15a9205ab7f60ca927767ad3de1a22705995bc043137fb2de1df457f3a6c63L1824

**Comment by CHonesetDoPa** [comment]
雾，收到，最近会把Normal分支完成并同时将issue#1解决掉（
