### ISSUE TITLE
对于电脑打开不是很友好....

### ISSUE THREAD

**Issue by LICKIL** [CHonesetDoPa/Mix-C#3]
打开就知道了

**Comment by CHonesetDoPa** [comment]
感谢你的issue。

嗯，是这样的，由于本项目是根据微信上小程序(实际上是个h5)进行的二次改动，这个现象在原版本中就有体现，如果合适的调整页面大小甚至还能让本来的游戏范围变得更大，原本的js也是为移动设备编写的(开发者估计也没想那么多嘿嘿)，所以就出现了这种奇怪的操作。

**提供的解决方案**:将浏览器拉伸缩放为长宽比为9:16或其他类似于手机显示的长宽比，这样可以在PC平台上玩耍了。

**可能**会在以后的日子里将样式固定
