### ISSUE TITLE
论几把

### ISSUE THREAD

**Issue by CHonesetDoPa** [CHonesetDoPa/Mix-C#4]
肥肠感谢大家的支持，这是C第一个不正经的项目（比正经的star还多）
由于某些不可抗力因素，现在的几把不算完整（虽然以后也不太可能完整）
就
再次感谢大家的资瓷！

**Comment by OCdes** [comment]
谁能不喜欢寄吧呢……😂

**Comment by stigchen2333** [comment]
啊这

**Comment by kuoitung** [comment]
游戏界面box的上下左右距离 能按照比例 自适应浏览器 就更加完美了
