### ISSUE TITLE
为什么玩不了？

### ISSUE THREAD

**Issue by Sirss** [CHonesetDoPa/Mix-C#9]
无论是手机端还是PC端都会加载到100%以后毫无反应，无论等了多久都是这个结果？还是说我打开姿势不对？

**Comment by CHonesetDoPa** [comment]
不妨试试这个链接http://mix-c-chonesetdopa.vercel.app/
github page
有时候会很卡

**Comment by CHonesetDoPa** [comment]
有可能是被举报了/GitHub Page抽风，不妨试试下载源码自行部署？

**Comment by ThanatosXingYu** [comment]
我的正常，换个服务器吧

**Comment by CHonesetDoPa** [comment]
同时可以试试vercel提供的镜像https://mix-c.vercel.app/

**Comment by Sirss** [comment]
> 同时可以试试vercel提供的镜像https://mix-c.vercel.app/

哇谢谢，这个可以

**Comment by CHonesetDoPa** [comment]
#5 问题已经解决
